### ISSUE TITLE
Having an issue downloading via BiocManager

### ISSUE THREAD

**Issue by aseyedia** [Nanostring-Biostats/GeoMxWorkflows#19]
Hello,

I am unable to install `GeoMxWorkflows` from Bioconductor. I am using R/4.2 and BiocManager version 3.15. When I do try to install `GeoMxWorkflows`, this is the error I am presented with:

```
> BiocManager::install("GeoMxWorkflows", force = TRUE, update = FALSE)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.15 (BiocManager 1.30.17), R 4.2.0 (2022-04-22)
Installing package(s) 'GeoMxWorkflows'
trying URL 'https://bioconductor.org/packages/3.15/workflows/src/contrib/GeoMxWorkflows_1.2.0.tar.gz'
Content type 'application/x-gzip' length 23646554 bytes (22.6 MB)
===================================
downloaded 16.1 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.15/workflows/src/contrib/GeoMxWorkflows_1.2.0.tar.gz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 16858657 != reported length 23646554
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://bioconductor.org/packages/3.15/workflows/src/contrib/GeoMxWorkflows_1.2.0.tar.gz': Timeout of 300 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘GeoMxWorkflows’ failed
```

I'm not sure where to go from here. When I manually enter https://bioconductor.org/packages/3.15/workflows/src/contrib/GeoMxWorkflows_1.2.0.tar.gz into my browser, I can unzip the package folder but I don't know how to install it from source. I also tried downloading and installing it using `devtools::install_github()`, but that did not work either. Please let me know if I'm doing anything wrong.

**Comment by aseyedia** [comment]
Update: was able to install from source in R using `install.packages("/path/GeoMxWorkflows/", repos = NULL, type="source")`

**Comment by NicoleEO** [comment]
Thanks for logging your issue. I'm glad you were able to install by source. We will investigate the download issue with Bioconductor.
Thank you,
Nicole
