### ISSUE TITLE
Bioconductor Version Discrepancy

### ISSUE THREAD

**Issue by danielnewhouse** [Nanostring-Biostats/GeoMxWorkflows#29]
https://github.com/Nanostring-Biostats/GeoMxWorkflows/blob/e9f783544fa4fa41cf7682e9bed853ec4e632329/vignettes/GeomxTools_RNA-NGS_Analysis.Rmd#L108

The vignette uses Bioconductor v3.17, not 3.15.

**Comment by maddygriz** [comment]
Good catch. I will update to say "LATEST.VERSION" so we don't have to keep updating that.
