### ISSUE TITLE
Work with initial dataset excel file from DSP analysis suite

### ISSUE THREAD

**Issue by aelhossiny** [Nanostring-Biostats/GeoMxWorkflows#8]
Hi, thank you for the great platform and analysis tool. I am trying to analyze some of my data but I can't seem to download the .dcc and .pkc file file from the DSP analysis suite. Can I create the object using the initial dataset excel file I export? 

Thanks!

**Comment by NicoleEO** [comment]
Hi @aelhossiny. It is possible to make a GeoMxSet object using the DA exports, but it is suggested to start from the dcc and pkc files as the DA exports are not natively read into the GeoMxSet object at this time. Please reach out to GeoMx Support <GeoMxSupport@nanostring.com> for help to get your dcc and pkc files. 
Thanks,
Nicole
